const DEFAULT_CUSTOM_CALENDAR_NOT_BUSY_MESSAGE = process.env.CUSTOM_CALENDAR_NOT_BUSY_MESSAGE || 'Calendar not busy.'
const DEFAULT_CUSTOM_CALENDAR_BUSY_MESSAGE = process.env.CUSTOM_CALENDAR_BUSY_MESSAGE || 'Calendar busy.'
const DEFAULT_CALENDAR_ID = process.env.GOOGLE_CALENDAR_ID || 'primary'
const DEFAULT_GOOGLE_TOKEN = process.env.GOOGLE_TOKEN
const DEFAULT_GOOGLE_CREDENTIALS = process.env.GOOGLE_CREDENTIALS

module.exports = {
  DEFAULT_CUSTOM_CALENDAR_NOT_BUSY_MESSAGE,
  DEFAULT_CUSTOM_CALENDAR_BUSY_MESSAGE,
  DEFAULT_CALENDAR_ID,
  DEFAULT_GOOGLE_TOKEN,
  DEFAULT_GOOGLE_CREDENTIALS,
}
