name: siesta
author: Typeform
description: Github Action checking if a Google Calendar it is busy or not, so you can schedule a Siesta.
inputs:
  google-credentials:
    description: contents of credentials.json
    required: true
  google-token:
    description: contents of token.json
    required: true
  google-calendar-id:
    description: the calendar id to check. If not specified, will take the primary calendar of that account
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'watch'
  color: 'green'

