name: Happy Path - Returns false
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  happy-path:
    runs-on: ubuntu-latest
    name: Returns false
    steps:
      - name: Given current branch is initialized
        uses: actions/checkout@v2
      - name: When a calendar with no events is checked
        uses: ./
        id: siesta
        with:
          google-credentials: ${{ secrets.siesta_google_credentials }}
          google-token: ${{ secrets.siesta_google_token }}
          google-calendar-id: ${{ secrets.siesta_google_calendar_id }}
          custom-calendar-busy-message: 'The Calendar is Busy'
          custom-calendar-not-busy-message: 'The Calendar is Not Busy'
          fail-if-busy: true
          hard-failure: true
      - name: Then the calendar is not busy
        uses: therussiankid92/gat@v1
        id: gat
        with:
          assertion: should.equal
          expected: false
          actual: ${{steps.siesta.outputs.calendar-busy}}
